import re
PRIMITIVE = {'i64', 'f64', 'bool', 'u64', 'u32', 'i32'}
def _rust_arg(name, typ):
    if name in ('self', 'cls'):
        return '&self' if name == 'self' else '&self'
    if typ == 'dynamic':
        return '{}: &str'.format(name)
    if typ in PRIMITIVE:
        return '{}: {}'.format(name, typ)
    if typ == 'String':
        return '{}: &str'.format(name)
    return '{}: &{}'.format(name, typ)
def _sanitize(val):
    if val is None:
        return 'String::new()'
    s = str(val).strip()
    if s in ('True', 'true'):
        return 'true'
    if s in ('False', 'false'):
        return 'false'
    if s == 'None':
        return 'None::<String>'
    if (s.startswith("'") and s.endswith("'")) or (s.startswith('"') and s.endswith('"')):
        inner = s[1:-1].replace('"', '\\"')
        return '"{}"'.format(inner)
    if re.match(r'^-?\d+$', s):
        return s
    if re.match(r'^-?\d+\.\d+$', s):
        return s
    if s.startswith('[') or s.startswith('{') or s.startswith('('):
        return 'Default::default()'
    return '"{}"'.format(s.replace('"', '\\"'))
class RustConverter:
    def __init__(self, mapper=None):
        self.mapper = mapper
    def convert(self, parsed):
        parts = [self._header(), self._imports(parsed), self._funcs(parsed), self._classes(parsed), self._vars(parsed)]
        return '\n\n'.join(p for p in parts if p.strip())
    def _header(self):
        return '// Generated by Swapify - https://crates.io - review before use'
    def _imports(self, parsed):
        lines = []
        has_hashmap = any('HashMap' in str(parsed.get('source', '')) for _ in [1]) or True
        lines.append('use std::collections::HashMap;')
        for imp in parsed.get('imports', []):
            mapped = self.mapper.map_library(imp['names'][0] if imp['type'] == 'import' else imp['module'])
            c = mapped.get('crate', '')
            if c and c not in ('std::fs', 'std::env', 'std::path', 'std::collections', 'std::process', 'std::thread') and '::' not in c:
                lines.append('use {};'.format(c))
        return '\n'.join(lines)
    def _funcs(self, parsed):
        funcs = [f for f in parsed.get('functions', []) if f['name'] != '__main__' and not f['name'].startswith('_')]
        # keep all but filter main guard later
        funcs = parsed.get('functions', [])
        if not funcs:
            return ''
        out = []
        for f in funcs:
            if f['name'] == '__main__':
                continue
            out.append(self._func(f))
        return '\n\n'.join(out)
    def _func(self, func):
        name = re.sub(r'^__', '', func['name'])
        name = re.sub(r'__$', '', name)
        if name == 'init':
            name = 'new'
        args = ', '.join(_rust_arg(a['name'], a['type']) for a in func['args'])
        ret = func['returns'] or ''
        body = self._body(func['body'])
        sig = 'fn {}({})'.format(name, args)
        if ret and ret != '()':
            sig += ' -> {}'.format(ret)
        return '{} {{\n{}\n}}'.format(sig, body)
    def _body(self, lines):
        if not lines:
            return '    // TODO'
        out = []
        for l in lines:
            r = self._py_to_rust(l)
            if r is None:
                continue
            for rl in r.split('\n'):
                out.append('    {}'.format(rl))
        if not out:
            return '    // TODO'
        return '\n'.join(out)
    def _classes(self, parsed):
        if not parsed.get('classes'):
            return ''
        out = []
        for cls in parsed['classes']:
            out.append(self._class(cls))
        return '\n\n'.join(out)
    def _class(self, cls):
        name = cls['name']
        fields = self._fields(cls)
        struct = 'struct {} {{\n{}\n}}'.format(name, '\n'.join('    pub {}: String,'.format(f) for f in fields) if fields else '    // no fields')
        impl_lines = []
        for m in cls.get('methods', []):
            mn = m['name']
            is_init = mn == '__init__'
            if is_init:
                args = [_rust_arg(a['name'], a['type']) for a in m['args'] if a['name'] not in ('self', 'cls')]
                body = self._body(m['body'])
                # map self.x = y  -> Self { x: y, ... }
                impl_lines.append('    pub fn new({}) -> Self {{\n{}\n        Self {{ {} }}\n    }}'.format(', '.join(args), body, ', '.join('{}: String::new()'.format(f) for f in fields) if fields else ''))
            else:
                args = ', '.join(_rust_arg(a['name'], a['type']) for a in m['args'])
                ret = m['returns'] or ''
                sig = '    fn {}({})'.format(mn, args)
                if ret:
                    sig += ' -> {}'.format(ret)
                impl_lines.append('{} {{\n{}\n    }}'.format(sig, self._body(m['body'])))
        if impl_lines:
            return '{}\n\nimpl {} {{\n{}\n}}'.format(struct, name, '\n\n'.join(impl_lines))
        return struct
    def _fields(self, cls):
        fields = []
        for line in cls.get('body', []):
            m = re.match(r'\s*self\.(\w+)\s*=', line)
            if m:
                fields.append(m.group(1))
        for m in cls.get('methods', []):
            if m['name'] == '__init__':
                for line in m['body']:
                    mm = re.match(r'\s*self\.(\w+)\s*=', line)
                    if mm and mm.group(1) not in fields:
                        fields.append(mm.group(1))
        return fields
    def _vars(self, parsed):
        if not parsed.get('variables'):
            return ''
        lines = []
        for v in parsed['variables']:
            lines.append('const {}: &str = {};'.format(v['name'].upper(), _sanitize(v['value'])))
        return '// module vars\n' + '\n'.join(lines) if lines else ''
    def _py_to_rust(self, line):
        if not line or not line.strip() or line.strip().startswith('#'):
            return None
        if '\n' in line:
            parts = []
            for sub in line.split('\n'):
                r = self._py_to_rust(sub)
                if r:
                    parts.append(r)
            j = '\n'.join(parts)
            o = j.count('{') - j.count('}')
            if o > 0:
                j += '\n' + '\n'.join(['}'] * o)
            return j
        s = line.strip()
        if s.startswith('def ') or s.startswith('class '):
            return None
        if s == 'pass':
            return '// pass'
        if s.startswith('import ') or s.startswith('from '):
            return '// {}'.format(s)
        if re.match(r'^if\s+__name__\s*==', s):
            return '// {}'.format(s)
        # control flow
        m = re.match(r'^for\s+(\w+)\s+in\s+(.+):$', s)
        if m:
            return 'for {} in {} {{'.format(m.group(1), self._expr(m.group(2)))
        m = re.match(r'^while\s+(.+):$', s)
        if m:
            return 'while {} {{'.format(self._expr(m.group(1)))
        m = re.match(r'^if\s+(.+):$', s)
        if m:
            return 'if {} {{'.format(self._expr(m.group(1)))
        m = re.match(r'^elif\s+(.+):$', s)
        if m:
            return '}} else if {} {{'.format(self._expr(m.group(1)))
        if s == 'else:':
            return '} else {'
        if s in ('try:', 'except:', 'except Exception:', 'finally:'):
            return '// {}'.format(s)
        if s.startswith('return '):
            return 'return {};'.format(self._expr(s[7:]))
        if s == 'return':
            return 'return;'
        if s.startswith('print('):
            inner = s[6:-1] if s.endswith(')') else s[6:]
            return 'println!("{{}}", {});'.format(self._expr(inner))
        if re.match(r'^[\w\.]+\s*=', s) and '==' not in s:
            # assignment
            parts = s.split('=', 1)
            lhs = parts[0].strip()
            rhs = self._expr(parts[1].strip())
            if lhs.startswith('self.'):
                return '{} = {};'.format(lhs, rhs)
            return 'let {} = {};'.format(lhs, rhs)
        # generic expression statement
        return '{};'.format(self._expr(s))
    def _expr(self, e):
        if not e:
            return 'Default::default()'
        s = e.strip()
        s = re.sub(r'\bTrue\b', 'true', s)
        s = re.sub(r'\bFalse\b', 'false', s)
        s = re.sub(r'\bNone\b', 'None', s)
        s = re.sub(r'\blen\(([^)]+)\)', r'\1.len()', s)
        s = re.sub(r'\.append\(', '.push(', s)
        s = re.sub(r'\bdict\(\)', 'HashMap::new()', s)
        s = re.sub(r'\blist\(\)', 'Vec::new()', s)
        s = re.sub(r'\bstr\(([^)]+)\)', r'String::from(\1)', s)
        s = re.sub(r'\bis\s+not\s+None\b', 'is_some()', s)
        s = re.sub(r'\bis\s+None\b', 'is_none()', s)
        s = re.sub(r'\bis\b', '==', s)
        s = re.sub(r'\bnot\s+in\b', '!contains', s)
        # single-quoted strings -> double-quoted
        def sq(m):
            inner = m.group(1).replace('"', '\\"')
            return '"{}"'.format(inner)
        s = re.sub(r"'([^']*)'", sq, s)
        # python string concat with + keep as format
        return s
