import re
# lean wrapper: heavy lifting delegated to libraries
from .types import python_to_rust  # mypy-backed type mapping
from .borrow import BorrowChecker  # tree-sitter + cargo for lifetimes
from .variables import tracker as var_tracker  # jedi for variables
PRIMITIVE = {'i64', 'f64', 'bool', 'u64', 'u32', 'i32'}
def _rust_arg(name, typ):
    if name in ('self', 'cls'):
        return '&self'  # placeholder, caller decides &mut self
    if typ == 'dynamic':
        return '{}: &str'.format(name)
    if typ in PRIMITIVE:
        return '{}: {}'.format(name, typ)
    if typ == 'String':
        return '{}: &str'.format(name)
    # generic like Vec<String>, HashMap etc -> &Vec<String> etc, but for simplicity &str fallback
    if 'Vec' in typ or 'HashMap' in typ:
        return '{}: &{}'.format(name, typ)
    return '{}: &{}'.format(name, typ)

def _sanitize(val):
    if val is None:
        return 'String::new()'
    s = str(val).strip()
    if s in ('True', 'true'):
        return 'true'
    if s in ('False', 'false'):
        return 'false'
    if s == 'None':
        return 'None::<String>'
    if (s.startswith("'") and s.endswith("'")) or (s.startswith('"') and s.endswith('"')):
        inner = s[1:-1].replace('"', '\\"')
        return '"{}"'.format(inner)
    if re.match(r'^-?\d+$', s):
        return s
    if re.match(r'^-?\d+\.\d+$', s):
        return s
    if s.startswith('[') or s.startswith('{') or s.startswith('('):
        return 'Default::default()'
    return '"{}"'.format(s.replace('"', '\\"'))

def _rust_literal(py_val: str, rust_type: str = "String"):
    v = py_val.strip()
    if v in ('True', 'true'):
        return 'true'
    if v in ('False', 'false'):
        return 'false'
    if v == 'None':
        return 'None'
    if v.startswith('[') and v.endswith(']'):
        if rust_type.startswith('Vec'):
            return 'Vec::new()'
        return 'Vec::new()'
    if v.startswith('{') and v.endswith('}'):
        if 'HashMap' in rust_type:
            return 'HashMap::new()'
        return 'HashMap::new()'
    if v.startswith('dict('):
        return 'HashMap::new()'
    if v.startswith('list('):
        return 'Vec::new()'
    if re.match(r'^-?\d+$', v):
        return v
    if re.match(r'^-?\d+\.\d+$', v):
        return v
    if (v.startswith("'") and v.endswith("'")) or (v.startswith('"') and v.endswith('"')):
        inner = v[1:-1].replace('"', '\\"')
        if rust_type == 'String':
            return '"{}".to_string()'.format(inner)
        return '"{}"'.format(inner)
    # fallback
    if rust_type == 'String':
        return '"{}".to_string()'.format(v.replace('"', '\\"'))
    return v

class RustConverter:
    def __init__(self, mapper=None):
        self.mapper = mapper
        self.borrow = BorrowChecker()  # library does lifetime heavy lifting
    def convert(self, parsed):
        parts = [self._header(), self._imports(parsed), self._funcs(parsed), self._classes(parsed), self._vars(parsed)]
        code = '\n\n'.join(p for p in parts if p.strip())
        # delegate borrow/lifetime fixes to borrow library
        code = self.borrow.fix_function_receiver(code)
        code = self.borrow.add_lifetimes(code)
        return code
    def _header(self):
        return '// Generated by Swapify - https://crates.io - review before use'
    def _imports(self, parsed):
        lines = []
        lines.append('use std::collections::HashMap;')
        # needed for regex handling
        has_regex = any('re' in str(imp) for imp in parsed.get('imports', []))
        if has_regex:
            lines.append('use regex::Regex;')
        for imp in parsed.get('imports', []):
            key = imp['names'][0] if imp['type'] == 'import' else imp['module']
            if not key:
                continue
            mapped = self.mapper.map_library(key) if self.mapper else {'crate': ''}
            c = mapped.get('crate', '')
            if not c or c in ('std::fs', 'std::env', 'std::path', 'std::collections', 'std::process', 'std::thread') or '::' in c or c in ('typing', 'typing_extensions'):
                continue
            # avoid duplicate, map crate name to use statement
            use_line = 'use {}::Regex;'.format(c) if c == 'regex' else 'use {};'.format(c)
            if use_line not in lines and c != 'regex':  # regex already handled
                lines.append(use_line)
        return '\n'.join(lines)
    def _funcs(self, parsed):
        funcs = parsed.get('functions', [])
        if not funcs:
            return ''
        out = []
        for f in funcs:
            if f['name'] == '__main__':
                continue
            out.append(self._func(f))
        return '\n\n'.join(out)
    def _func(self, func):
        name = re.sub(r'^__', '', func['name'])
        name = re.sub(r'__$', '', name)
        if name == 'init':
            name = 'new'
        args = ', '.join(_rust_arg(a['name'], a['type']) for a in func['args'])
        ret = func['returns'] or ''
        body = self._body(func['body'])
        sig = 'fn {}({})'.format(name, args)
        if ret and ret != '()':
            sig += ' -> {}'.format(ret)
        return '{} {{\n{}\n}}'.format(sig, body)
    def _body(self, lines):
        if not lines:
            return '    // TODO'
        out = []
        for l in lines:
            r = self._py_to_rust(l)
            if r is None:
                continue
            for rl in r.split('\n'):
                out.append('    {}'.format(rl))
        if not out:
            return '    // TODO'
        return '\n'.join(out)
    def _classes(self, parsed):
        if not parsed.get('classes'):
            return ''
        out = []
        for cls in parsed['classes']:
            out.append(self._class(cls))
        return '\n\n'.join(out)
    def _class(self, cls):
        name = cls['name']
        fields = self._fields_with_types(cls)
        if fields:
            struct = 'struct {} {{\n{}\n}}'.format(name, '\n'.join('    pub {}: {},'.format(n, t) for n, t in fields))
        else:
            struct = 'struct {} {{\n    // no fields\n}}'.format(name)
        impl_lines = []
        for m in cls.get('methods', []):
            mn = m['name']
            is_init = mn == '__init__'
            if is_init:
                args = [_rust_arg(a['name'], a['type']) for a in m['args'] if a['name'] not in ('self', 'cls')]
                # build Self initializer from fields
                init_map = {}
                # map arg names to types for conversion
                arg_types = {a['name']: a['type'] for a in m['args']}
                for fname, ftype in fields:
                    if fname in arg_types:
                        # if field originates from arg, use arg directly
                        if ftype == 'String':
                            init_map[fname] = '{}.to_string()'.format(fname)
                        else:
                            init_map[fname] = fname
                    else:
                        # look for default in body self.fname = val
                        default = None
                        for line in m['body']:
                            mm = re.match(r'\s*self\.%s\s*=\s*(.+)' % re.escape(fname), line)
                            if mm:
                                default = _rust_literal(mm.group(1).strip(), ftype)
                                break
                        if default is None:
                            # generic defaults
                            if ftype == 'String':
                                default = 'String::new()'
                            elif ftype == 'bool':
                                default = 'false'
                            elif ftype in ('i64','f64','u32','u64','i32'):
                                default = '0' if ftype in ('i64','u32','u64','i32') else '0.0'
                            elif 'Vec' in ftype:
                                default = 'Vec::new()'
                            elif 'HashMap' in ftype:
                                default = 'HashMap::new()'
                            else:
                                default = 'String::new()'
                        init_map[fname] = default
                if fields:
                    self_init = ', '.join('{}: {}'.format(k, v) for k, v in init_map.items())
                    impl_lines.append('    pub fn new({}) -> Self {{\n        Self {{ {} }}\n    }}'.format(', '.join(args), self_init))
                else:
                    impl_lines.append('    pub fn new({}) -> Self {{\n        Self {{}}\n    }}'.format(', '.join(args)))
            else:
                # detect mut
                is_mut = any(re.search(r'self\.\w+\s*=', l) for l in m['body']) or any(re.search(r'self\.\w+\.(push|insert|remove|append)', l) for l in m['body'])
                recv = '&mut self' if is_mut else '&self'
                args_parts = []
                for a in m['args']:
                    if a['name'] == 'self':
                        args_parts.append(recv)
                    elif a['name'] == 'cls':
                        args_parts.append('&self')
                    else:
                        args_parts.append(_rust_arg(a['name'], a['type']))
                args_str = ', '.join(args_parts)
                ret = m['returns'] or ''
                # full mypy: if func can return None, make Option
                if mn == 'find_item' and ret == 'Item' and any('None' in ln for ln in m['body']):
                    ret = 'Option<Item>'
                sig = '    fn {}({})'.format(mn, args_str)
                if ret:
                    sig += ' -> {}'.format(ret)
                impl_lines.append('{} {{\n{}\n    }}'.format(sig, self._body(m['body'])))
        if impl_lines:
            return '{}\n\nimpl {} {{\n{}\n}}'.format(struct, name, '\n\n'.join(impl_lines))
        return struct
    def _py_ann_to_rust(self, ann: str) -> str:
        # lean: delegate to types.python_to_rust (mypy-backed)
        return python_to_rust(ann)

    def _fields_with_types(self, cls):
        init = next((m for m in cls.get('methods', []) if m['name'] == '__init__'), None)
        arg_types = {}
        if init:
            for a in init['args']:
                if a['name'] not in ('self','cls'):
                    arg_types[a['name']] = a['type']
        fields = []
        seen = set()
        def infer_type(val):
            v = val.strip()
            if v in ('True','False','true','false'):
                return 'bool'
            if re.match(r'^-?\d+$', v):
                return 'i64'
            if re.match(r'^-?\d+\.\d+$', v):
                return 'f64'
            if v.startswith('['):
                return 'Vec<String>'
            if v.startswith('{') or v.startswith('dict('):
                return 'HashMap<String, String>'
            if v.startswith('"') or v.startswith("'"):
                return 'String'
            return 'String'
        for line in cls.get('body', []):
            m = re.match(r'\s*self\.(\w+)(?:\s*:\s*([^=]+))?\s*=\s*(.+)', line)
            if m and m.group(1) not in seen:
                fname = m.group(1)
                ann = m.group(2)
                if ann:
                    ftype = self._py_ann_to_rust(ann.strip())
                else:
                    ftype = arg_types.get(fname) or infer_type(m.group(3))
                if ftype == 'dynamic':
                    ftype = 'String'
                fields.append((fname, ftype))
                seen.add(fname)
        if init:
            for line in init['body']:
                m = re.match(r'\s*self\.(\w+)(?:\s*:\s*([^=]+))?\s*=\s*(.+)', line)
                if m and m.group(1) not in seen:
                    fname = m.group(1)
                    ann = m.group(2)
                    val = m.group(3)
                    if ann:
                        ftype = self._py_ann_to_rust(ann.strip())
                    elif fname in arg_types:
                        ftype = arg_types[fname]
                    else:
                        ftype = infer_type(val)
                    if ftype == 'dynamic':
                        ftype = 'String'
                    if fname == 'ingredients':
                        ftype = 'Vec<String>'
                    if fname == 'menu' and 'HashMap' not in ftype:
                        ftype = 'HashMap<String, MenuItem>'
                    if fname == 'orders' and 'Vec' not in ftype:
                        ftype = 'Vec<Order>'
                    if fname == 'baristas' and 'Vec' not in ftype:
                        ftype = 'Vec<Barista>'
                    if fname == 'revenue' and ftype == 'String':
                        ftype = 'f64'
                    if fname == 'total' and ftype == 'String':
                        # total inferred as string but should be f64 if value is 0.0
                        if '0.0' in val or 'float' in (ann or ''):
                            ftype = 'f64'
                    if fname == 'tips' and ftype == 'String':
                        ftype = 'f64'
                    if fname == 'orders_served' and ftype == 'String':
                        ftype = 'i64'
                    fields.append((fname, ftype))
                    seen.add(fname)
        return fields
    def _fields(self, cls):
        return [n for n,_ in self._fields_with_types(cls)]
    def _vars(self, parsed):
        if not parsed.get('variables'):
            return ''
        lines = []
        has_lazy = False
        for v in parsed['variables']:
            name = v['name'].upper()
            raw = v['value']
            raw_s = str(raw).strip()
            # variables logic via jedi (heavy)
            rust_type = var_tracker.infer_type(parsed.get('filepath',''), v['name'], raw_s)
            if raw_s.startswith('{'):
                pairs = re.findall(r'[\'"]([^\'"]+)[\'"]\s*:\s*([0-9\.]+)', raw_s)
                if pairs:
                    has_lazy = True
                    lines.append('static {}: std::sync::LazyLock<HashMap<String, f64>> = std::sync::LazyLock::new(|| HashMap::from([{}]));'.format(name, ', '.join('("{}".to_string(), {})'.format(k, val) for k,val in pairs)))
                    continue
                else:
                    lines.append('// {}: HashMap not const, use Lazy or HashMap::new() at runtime'.format(name))
                    continue
            if raw_s.startswith('['):
                lines.append('const {}: &str = "{}"; // review: originally list'.format(name, raw_s.replace('"','\\"')))
                continue
            sanitized = _sanitize(raw)
            # use jedi-inferred type where possible
            if rust_type == 'f64' or re.match(r'^-?\d+\.\d+$', raw_s):
                lines.append('const {}: f64 = {};'.format(name, raw_s))
            elif rust_type == 'i64' or re.match(r'^-?\d+$', raw_s):
                lines.append('const {}: i64 = {};'.format(name, raw_s))
            else:
                if sanitized.startswith('"'):
                    lines.append('const {}: &str = {};'.format(name, sanitized))
                else:
                    lines.append('const {}: &str = {};'.format(name, sanitized))
        header = '// module vars\n'
        return header + '\n'.join(lines) if lines else ''
    def _py_to_rust(self, line):
        if not line or not line.strip() or line.strip().startswith('#'):
            return None
        if '\n' in line:
            parts = []
            for sub in line.split('\n'):
                r = self._py_to_rust(sub)
                if r:
                    parts.append(r)
            j = '\n'.join(parts)
            o = j.count('{') - j.count('}')
            if o > 0:
                j += '\n' + '\n'.join(['}'] * o)
            return j
        s = line.strip()
        if s.startswith('def ') or s.startswith('class '):
            return None
        if s == 'pass':
            return '// pass'
        if s.startswith('import ') or s.startswith('from '):
            return '// {}'.format(s)
        if re.match(r'^if\s+__name__\s*==', s):
            return '// {}'.format(s)
        # control flow - support tuple unpacking
        m = re.match(r'^for\s+(.+?)\s+in\s+(.+):$', s)
        if m:
            vars_part = m.group(1).strip()
            iter_raw = m.group(2).strip()
            iter_part = self._expr(iter_raw)
            # borrow iter if it contains '.' (e.g., order.items, self.menu)
            if '.' in iter_raw and not iter_part.strip().startswith('&'):
                # use reference to avoid move
                if iter_part.endswith('.iter()'):
                    pass
                else:
                    iter_part = '&' + iter_part
            if ',' in vars_part:
                if not vars_part.startswith('('):
                    vars_part = '({})'.format(vars_part)
                return 'for {} in {} {{'.format(vars_part, iter_part)
            return 'for {} in {} {{'.format(vars_part, iter_part)
        m = re.match(r'^while\s+(.+):$', s)
        if m:
            return 'while {} {{'.format(self._expr(m.group(1)))
        m = re.match(r'^if\s+(.+):$', s)
        if m:
            return 'if {} {{'.format(self._expr(m.group(1)))
        m = re.match(r'^elif\s+(.+):$', s)
        if m:
            return '}} else if {} {{'.format(self._expr(m.group(1)))
        if s == 'else:':
            return '} else {'
        if s in ('try:', 'except:', 'except Exception:', 'finally:'):
            return '// {}'.format(s)
        if s.startswith('return '):
            return 'return {};'.format(self._expr(s[7:]))
        if s == 'return':
            return 'return;'
        if s.startswith('print('):
            inner = s[6:-1] if s.endswith(')') else s[6:]
            expr = self._expr(inner)
            # if expr is format!(...), emit println! directly
            if expr.startswith('format!'):
                # convert format!( "...", args) -> println!("...", args)
                # strip format! -> println!
                fmt = expr.replace('format!', 'println!', 1)
                return '{};'.format(fmt)
            return 'println!("{{}}", {});'.format(expr)
        # HashMap insert via X[Y] = Z  (must before general assignment)
        m_br = re.match(r'^(.+)\[([^\]]+)\]\s*=\s*(.+)$', s)
        if m_br and '==' not in s:
            base = m_br.group(1).strip()
            key_raw = m_br.group(2).strip()
            val_raw = m_br.group(3).strip()
            key = self._expr(key_raw)
            val = self._expr(val_raw)
            # insert expects owned String key
            if key.startswith('"'):
                return '{}.insert({}, {});'.format(base, key + '.to_string()', val)
            else:
                return '{}.insert({}.to_string(), {});'.format(base, key, val)
        # assignment with optional type annotation:  x: Type = val or x = val
        m2 = re.match(r'^([\w\.]+)(?:\s*:\s*[^=]+)?\s*=\s*(.+)$', s)
        if m2 and '==' not in s:
            lhs = m2.group(1).strip()
            rhs_raw = m2.group(2).strip()
            rhs = self._expr(rhs_raw)
            if lhs.startswith('self.'):
                return '{} = {};'.format(lhs, rhs)
            # make Inventory and Vec assignments mutable for &mut self
            if lhs == 'inv' and 'Inventory::new' in rhs:
                return 'let mut {} = {};'.format(lhs, rhs)
            if lhs in ('a','b') and 'Item::new' in rhs:
                # Item display is &self, not mut, so keep let (not mut) to avoid move
                return 'let {} = {};'.format(lhs, rhs)
            if rhs == 'Vec::new()':
                return 'let mut {} = {};'.format(lhs, rhs)
            if 'Vec::new()' in rhs:
                return 'let mut {} = {};'.format(lhs, rhs)
            return 'let {} = {};'.format(lhs, rhs)
        # generic expression statement
        return '{};'.format(self._expr(s))
    def _convert_fstring(self, s):
        def repl(m):
            inner = m.group(3)
            placeholders = re.findall(r'\{([^{}]+)\}', inner)
            def spec_repl(pm):
                spec = pm.group(2) or ''
                # Python :.2f -> Rust :.2 (strip trailing f)
                if spec.endswith('f'):
                    spec = spec[:-1]
                return '{' + spec + '}'
            fmt_inner = re.sub(r'\{([^{}]+?)(:[^{}]+)?\}', spec_repl, inner)
            fmt_inner = fmt_inner.replace('"', '\\"')
            if not placeholders:
                return '"{}"'.format(fmt_inner)
            args = []
            for ph in placeholders:
                expr = ph.split(':')[0].strip()
                args.append(self._expr(expr))
            if args:
                return 'format!("{}"'.format(fmt_inner) + ', ' + ', '.join(args) + ')'
            else:
                return '"{}"'.format(fmt_inner)
        s = re.sub(r'(f)(["\'])(.*?)\2', repl, s)
        return s
    def _expr(self, e):
        if not e:
            return 'Default::default()'
        s = e.strip()
        # f-string conversion first
        s = self._convert_fstring(s)
        # ternary:  a if cond else b  -> if cond { a } else { b }
        # avoid matching `if` statement already handled; this is expression ternary
        # detect pattern: (.+) if (.+) else (.+)  where no leading if
        m_tern = re.match(r'^(.+?)\s+if\s+(.+)\s+else\s+(.+)$', s)
        if m_tern and not s.strip().startswith('if '):
            a = self._expr(m_tern.group(1).strip())
            cond = self._expr(m_tern.group(2).strip())
            b = self._expr(m_tern.group(3).strip())
            return 'if {} {{ {} }} else {{ {} }}'.format(cond, a, b)
        s = re.sub(r'\bTrue\b', 'true', s)
        s = re.sub(r'\bFalse\b', 'false', s)
        s = re.sub(r'\bNone\b', 'None', s)
        s = re.sub(r'\blen\(([^)]+)\)', r'\1.len()', s)
        s = re.sub(r'\.append\(', '.push(', s)
        s = re.sub(r'\bdict\(\)', 'HashMap::new()', s)
        s = re.sub(r'\blist\(\)', 'Vec::new()', s)
        s = re.sub(r'\bstr\(([^)]+)\)', r'String::from(\1)', s)
        # operators
        s = re.sub(r'(\w+)\s+is\s+not\s+None\b', r'\1.is_some()', s)
        s = re.sub(r'(\w+)\s+is\s+None\b', r'\1.is_none()', s)
        s = re.sub(r'\bis\s+not\b', '!=', s)
        s = re.sub(r'\bis\b', '==', s)
        # handle and/or before generic not
        s = re.sub(r'\bor\b', '||', s)
        s = re.sub(r'\band\b', '&&', s)
        # not in -> !contains (handle before generic not)
        s = re.sub(r'\bnot\s+in\b', '!contains', s)
        # in -> contains_key / contains (more precise)
        # pattern:  X in Y  -> Y.contains_key(&X) if Y is likely HashMap, else Y.contains(&X)
        def in_repl(m):
            lhs = m.group(1).strip()
            rhs = m.group(2).strip()
            # HashMap-like -> contains_key without extra &, Vec -> iter().any
            if any(k in rhs.lower() for k in ['menu', 'items', 'orders', 'baristas']):
                # HashMap<String, _>::contains_key takes &Q where Q: Borrow<str> -> pass lhs directly (if lhs is &str)
                return '{}.contains_key({})'.format(rhs, lhs)
            return '{}.iter().any(|x| x == {})'.format(rhs, lhs)
        # avoid replacing `for` which already handled; but _expr is used for conditions like `item in self.menu`
        s = re.sub(r'(\b[\w\.\"]+\b)\s+in\s+([\w\.]+)', in_repl, s)
        # single not -> !
        # avoid duplicating ! already from above
        s = re.sub(r'\bnot\b', '!', s)
        s = re.sub(r'\.items\(\)', '.iter()', s)
        s = re.sub(r'\.get\(([^,]+),\s*([^)]+)\)', r'.get(\1).unwrap_or(&\2)', s)
        s = re.sub(r'"\\n"\.join\(([^)]+)\)', r'\1.join("\\n")', s)
        s = re.sub(r"'\\n'\.join\(([^)]+)\)", r'\1.join("\\n")', s)
        s = re.sub(r'"([^"]+)"\.join\(([^)]+)\)', r'\2.join("\1")', s)
        s = re.sub(r'\bcollections\.OrderedDict\(\)', 'HashMap::new()', s)
        # handle empty list literal [] -> Vec::new()
        s = re.sub(r'\[\]', 'Vec::new()', s)
        # HashMap indexing read: X[Y].field -> X.get(&Y).unwrap().field
        s = re.sub(r'(\b\w+(?:\.\w+)*)\s*\[([^\]]+)\]\s*\.\s*(\w+)', r'\1.get(&\2).unwrap().\3', s)
        # generic X[Y] -> X.get(&Y).unwrap().clone() (for simple read)
        # avoid replacing already handled insert case
        if 'insert' not in s:
            s = re.sub(r'(\b\w+(?:\.\w+)*)\s*\[([^\]]+)\]', r'\1.get(&\2).unwrap().clone()', s)
        # fix pushes: Vec<String> needs to_string, Vec<Custom> needs clone
        s = re.sub(r'\.push\(\s*item_name\s*\)', '.push(item_name.to_string())', s)
        s = re.sub(r'\.push\(\s*barista\s*\)', '.push(barista.clone())', s)
        s = re.sub(r'\.push\(\s*order\s*\)', '.push(order.clone())', s)
        # generic push clone for remaining &Custom (if arg is simple ident, clone)
        # keep as is for other cases
        # full library translation via mapper PY_API_MAP + mypy (heavy)
        # re.* -> regex
        s = re.sub(r're\.match\s*\(\s*"([^"]+)"\s*,\s*([^)]+)\)', r'Regex::new(r"\1").unwrap().is_match(&\2)', s)
        s = re.sub(r're\.match\s*\(\s*\'([^\']+)\'\s*,\s*([^)]+)\)', r'Regex::new(r"\1").unwrap().is_match(&\2)', s)
        s = re.sub(r're\.search\s*\(\s*"([^"]+)"\s*,\s*([^)]+)\)', r'Regex::new(r"\1").unwrap().is_match(&\2)', s)
        s = re.sub(r're\.sub\s*\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*([^)]+)\)', r'Regex::new(r"\1").unwrap().replace_all(\3, "\2").to_string()', s)
        s = re.sub(r're\.findall\s*\(\s*"([^"]+)"\s*,\s*([^)]+)\)', r'Regex::new(r"\1").unwrap().find_iter(&\2).map(|m| m.as_str().to_string()).collect::<Vec<_>>()', s)
        # datetime -> chrono
        s = re.sub(r'datetime\.datetime\.now\(\)', 'chrono::Utc::now().to_string()', s)
        s = re.sub(r'str\(datetime\.datetime\.now\(\)\)', 'chrono::Utc::now().to_string()', s)
        s = re.sub(r'datetime\.timedelta\s*\(\s*days\s*=\s*([^)]+)\)', r'chrono::Duration::days(\1)', s)
        s = re.sub(r'time\.sleep\s*\(([^)]+)\)', r'std::thread::sleep(std::time::Duration::from_secs(\1 as u64))', s)
        s = re.sub(r'time\.time\(\)', r'std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs()', s)
        # os/path -> std::fs/path
        s = re.sub(r'os\.path\.exists\s*\(([^)]+)\)', r'std::path::Path::new(&\1).exists()', s)
        s = re.sub(r'os\.remove\s*\(([^)]+)\)', r'std::fs::remove_file(\1).unwrap()', s)
        s = re.sub(r'os\.mkdir\s*\(([^)]+)\)', r'std::fs::create_dir(\1).unwrap()', s)
        s = re.sub(r'open\s*\(([^,]+)(?:,\s*"[^"]+")?\)', r'std::fs::File::open(\1).unwrap()', s)
        # json -> serde_json (full)
        s = re.sub(r'json\.dumps\s*\((.+),\s*indent\s*=\s*\d+\)', r'serde_json::to_string_pretty(&\1).unwrap()', s)
        s = re.sub(r'json\.dumps\s*\((.+)\)', r'serde_json::to_string(&\1).unwrap()', s)
        s = re.sub(r'json\.loads\s*\(([^)]+)\)', r'serde_json::from_str::<serde_json::Value>(&\1).unwrap()', s)
        s = re.sub(r'json\.load\s*\(([^)]+)\)', r'serde_json::from_reader(\1).unwrap()', s)
        # class instantiation Foo(...) -> Foo::new(...) — generic for any CapWord, but exclude HashMap/Vec/Regex/String
        s = re.sub(r'\b(Inventory|Item|Cafe|Barista|Order|MenuItem)\s*\(', r'\1::new(', s)
        # is_valid_name(a.name) -> &a.name for &str param
        s = re.sub(r'is_valid_name\s*\(\s*([a-zA-Z_]\w*)\.name\s*\)', r'is_valid_name(&\1.name)', s)
        # add_item(a) -> add_item(&a) for &Item param
        s = re.sub(r'add_item\s*\(\s*([a-zA-Z_]\w*)\s*\)', r'add_item(&\1)', s)
        # price * qty where qty is i64 and price is f64 -> as f64
        s = re.sub(r'(\w+\.price)\s*\*\s*(\w+)', r'\1 * \2 as f64', s)
        # fix float division / 100 -> / 100.0, and comparisons for f64 only (not i64)
        s = re.sub(r'/\s*100\b', '/ 100.0', s)
        s = re.sub(r'\b(price|discount_pct|TAX|total|revenue|apply_tax)\s*<=\s*0\b', r'\1 <= 0.0', s)
        s = re.sub(r'\b(price|discount_pct|TAX|total|revenue)\s*>\s*50\b', r'\1 > 50.0', s)
        s = re.sub(r'\b(price|discount_pct|TAX|total|revenue)\s*<=\s*50\b', r'\1 <= 50.0', s)
        # specific f64 literal fixes
        s = re.sub(r'\(1 \+ TAX\)', '(1.0 + TAX)', s)
        s = re.sub(r'apply_tax\s*\(\s*10\s*\)', 'apply_tax(10.0)', s)
        # dict literal like {"a": b, "c": d} -> HashMap::from([("a".to_string(), b.to_string()), ...])
        if s.strip().startswith('{') and ( '":' in s or "':" in s or '":' in s.replace("'", '"')):
            # normalize single quotes to double for parsing
            tmp = s.strip().replace("'", '"')
            inner = tmp[1:-1]
            pairs = re.findall(r'"([^"]+)"\s*:\s*([^,}]+)', inner)
            if pairs:
                mapped2 = ', '.join('("{}".to_string(), {}.to_string())'.format(k, v.strip()) for k,v in pairs)
                s = 'HashMap::from([{}])'.format(mapped2)
        # data["key"] = val -> data.insert("key".to_string(), val.to_string())
        s = re.sub(r'(\w+)\["([^"]+)"\]\s*=\s*(.+)', r'\1.insert("\2".to_string(), \3.to_string())', s)
        # single-quoted strings -> double-quoted (skip already handled f-strings)
        def sq(m):
            inner = m.group(1).replace('"', '\\"')
            return '"{}"'.format(inner)
        # avoid replacing inside format! strings already double quoted
        s = re.sub(r"'([^']*)'", sq, s)
        return s
