// Generated by Swapify - https://crates.io - review before use

use std::collections::HashMap;
use regex::Regex;
use serde_json;
use chrono;

fn format_price(price: f64) -> String {
    return format!("${:.2}", price);
}

fn apply_discount(total: f64, discount_pct: f64) -> f64 {
    if discount_pct <= 0.0 || discount_pct > 50.0 {
    return total;
    }
    let discount = total * (discount_pct / 100.0);
    return total - discount;
}

fn is_valid_customer(name: &str) -> bool {
    if name.len() < 2 {
    return false;
    }
    if ! Regex::new(r"^[A-Za-z ]+$").unwrap().is_match(&name) {
    return false;
    }
    return true;
}

fn main() {
    let cafe = Cafe::new(SHOP_NAME);
    let barista = Barista::new("Alex", 3);
    cafe.add_barista(barista);
    cafe.show_menu();
    println!("{}", barista.greet("Sam"));
    let order = cafe.place_order("Sam", ["latte", "espresso", "mocha"]);
    println!("{}", barista.make_coffee(order));
    let total = order.calculate_total();
    println!("Total with tax: {}", format_price(total));
    let discounted = apply_discount(total, 10);
    println!("With 10% discount: {}", format_price(discounted));
    cafe.complete_order(order.order_id);
    println!("{}", cafe.daily_report());
    println!("{}", cafe.to_json());
    barista.add_tip(2.5);
    println!("Barista stats: {}", barista.get_stats());
}

struct MenuItem {
    pub name: String,
    pub price: f64,
    pub ingredients: Vec<String>,
    pub available: bool,
}

impl MenuItem {
    pub fn new(name: &str, price: f64, ingredients: &Vec<String>) -> Self {
        Self { name: name.to_string(), price: price, ingredients: ingredients, available: true }
    }

    fn display(&self) -> String {
    let status = if self.available { "available" } else { "out of stock" };
    return format!("{} - ${:.2} ({})", self.name, self.price, status);
    }

    fn update_price(&mut self, new_price: f64) -> bool {
    if new_price > 0 {
    self.price = new_price;
    return true;
    }
    return false;
    }
}

struct Order {
    pub order_id: i64,
    pub customer_name: String,
    pub items: Vec<String>,
    pub total: f64,
    pub status: String,
}

impl Order {
    pub fn new(order_id: i64, customer_name: &str) -> Self {
        Self { order_id: order_id, customer_name: customer_name.to_string(), items: Vec::new(), total: 0.0, status: "pending".to_string() }
    }

    fn add_item(&mut self, item_name: &str, price: f64) {
    self.items.push(item_name.to_string());
    self.total += price;
    println!("Added {} to order {}", item_name, self.order_id);
    }

    fn remove_item(&mut self, item_name: &str) -> bool {
    if self.items.contains(&item_name) {
    self.items.remove(item_name);
    self.total -= MENU.get(item_name).unwrap_or(&0);
    return true;
    }
    return false;
    }

    fn calculate_total(&self) -> f64 {
    let subtotal = self.total;
    let tax = subtotal * TAX_RATE;
    return subtotal + tax;
    }

    fn complete(&mut self) {
    self.status = "completed";
    println!("Order {} for {} completed!", self.order_id, self.customer_name);
    }
}

struct Barista {
    pub name: String,
    pub experience: i64,
    pub orders_served: i64,
    pub tips: f64,
}

impl Barista {
    pub fn new(name: &str, experience: i64) -> Self {
        Self { name: name.to_string(), experience: experience, orders_served: 0, tips: 0.0 }
    }

    fn greet(&self, customer: &str) -> String {
    return format!("Hello {}! I'm {}, your barista today.", customer, self.name);
    }

    fn make_coffee(&self, order: &Order) -> String {
    let mut result = Vec::new();
    for item in &order.items {
    if MENU.contains_key(&item) {
    result.push(format!("Brewing {}...", item));
    } else {
    result.push(format!("Unknown item: {}", item));
    }
    }
    self.orders_served += 1;
    if order.items.len() == 0 {
    return "No items to prepare";
    }
    return result.join("\n");
    }

    fn add_tip(&self, amount: f64) {
    if amount > 0 {
    self.tips += amount;
    println!("Thanks for ${:.2} tip!", amount);
    }
    }

    fn get_stats(&self) -> HashMap<String,String> {
    return {"name": self.name, "served": self.orders_served, "tips": self.tips, "experience": self.experience};
    }
}

struct Cafe {
    pub name: String,
    pub menu: HashMap<String, MenuItem>,
    pub orders: Vec<Order>,
    pub baristas: Vec<Barista>,
    pub revenue: f64,
}

impl Cafe {
    pub fn new(name: &str) -> Self {
        Self { name: name.to_string(), menu: HashMap::new(), orders: Vec::new(), baristas: Vec::new(), revenue: 0.0 }
    }

    fn _init_menu(&self) {
    for (item_name, price) in MENU.iter() {
    let ingredients = ["coffee", "water"];
    if item_name == "latte" {
    ingredients.push("milk");
    } else if item_name == "mocha" {
    ingredients.extend(["milk", "chocolate"]);
    self.menu.insert(item_name.to_string(), MenuItem::new(item_name, price, ingredients));
    }
    }
    }

    fn add_barista(&mut self, barista: &Barista) {
    self.baristas.push(barista.clone());
    println!("Barista {} joined {}", barista.name, self.name);
    }

    fn place_order(&mut self, customer_name: &str, items: &Vec<String>) -> Order {
    let order_id = self.orders.len() + 1;
    let order = Order::new(order_id, customer_name);
    for item in items {
    if self.menu.contains_key(&item) && self.menu.get(&item).unwrap().available {
    order.add_item(item, self.menu.get(&item).unwrap().price);
    } else {
    println!("Sorry, {} ! available", item);
    }
    }
    self.orders.push(order.clone());
    return order;
    }

    fn complete_order(&self, order_id: i64) -> bool {
    for order in &self.orders {
    if order.order_id == order_id {
    if order.status == "pending" {
    order.complete();
    let total = order.calculate_total();
    self.revenue += total;
    println!("Revenue now ${:.2}", self.revenue);
    return true;
    } else {
    println!("Order {} already {}", order_id, order.status);
    return false;
    }
    }
    }
    println!("Order {} ! found", order_id);
    return false;
    }

    fn show_menu(&self) {
    println!("--- {} Menu ---", self.name);
    for (name, item) in self.menu.iter() {
    println!("{}", item.display());
    }
    }

    fn daily_report(&self) -> String {
    let count = self.orders.len();
    let pending = 0;
    for o in &self.orders {
    if o.status == "pending" {
    pending += 1;
    }
    }
    let completed = count - pending;
    let report = format!("Cafe {}: {}/{} completed, Revenue ${:.2}", self.name, completed, count, self.revenue);
    if Regex::new(r"^[A-Za-z &]+$").unwrap().is_match(&self.name) {
    report += " [valid name]";
    }
    return report;
    }

    fn to_json(&self) -> String {
    let data = HashMap::new();
    data.insert("shop".to_string(), self.name);
    data.insert("revenue".to_string(), self.revenue);
    data.insert("orders".to_string(), self.orders.len());
    data.insert("date".to_string(), String::from(chrono::Utc::now().to_string()));
    return serde_json::to_string_pretty(&data).unwrap();
    }
}

// module vars
static MENU: std::sync::LazyLock<HashMap<String, f64>> = std::sync::LazyLock::new(|| HashMap::from([("espresso".to_string(), 3.5), ("latte".to_string(), 4.5), ("cappuccino".to_string(), 4.0), ("americano".to_string(), 3.0), ("mocha".to_string(), 5.0), ("cold_brew".to_string(), 4.25)]));
const TAX_RATE: f64 = 0.08;
const SHOP_NAME: &str = "Rust & Roast Cafe";